### ISSUE TITLE
Look into how to use the same time as the host machine

### ISSUE THREAD

**Issue by victor73** [Virome-Collaboration-Group/Virome-Pipeline-Docker#3]
The container seems to be in another timezone, or perhaps using/displaying universal time. Look into how this can be made to match the local host machine's time.

**Comment by blueagave** [comment]
One option is to set the TZ environment variable during run time using the "-e" option:

$ date
Fri Jun 17 14:52:17 EDT 2016

$ docker run --rm -t -i ubuntu date
Fri Jun 17 18:52:22 UTC 2016

$ docker run --rm -t -i -e TZ=America/New_York ubuntu date
Fri Jun 17 14:52:25 EDT 2016

Of course this necessitates knowing the desired timezone value.

**Comment by blueagave** [comment]
Perhaps more thorough setting the timezone-related files:

In the Dockerfile:

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

Override the default TZ environment variable at runtime, if necessary:

$ date
Fri Jun 17 15:47:13 EDT 2016

$ docker run --rm -ti zippy:1.0 date
Fri Jun 17 15:47:18 EDT 2016

$ docker run --rm -ti -e TZ=America/Chicago zippy:1.0 date
Fri Jun 17 14:47:22 CDT 2016

**Comment by victor73** [comment]
Documented.
