### ISSUE TITLE
Use the USER directive to enhance security

### ISSUE THREAD

**Issue by victor73** [Virome-Collaboration-Group/Virome-Pipeline-Docker#8]
I believe that by default, the user that is executing the pipeline inside the container would be root since we are not using the USER directive. We should attempt to correct that by adding a user followed by a USER directive, or attempting to run it as "nobody".

**Comment by blueagave** [comment]
Modified the Dockerfile to run the execute_pipeline.sh script (and start apache) as the "virome" user.
